version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
    command: redis-server --bind 0.0.0.0
    volumes:
      - 'redis:/data'
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/getting_started_blog
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/getting_started_blog
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
volumes:
  redis:
  postgres: