default: &default
  adapter: postgresql
  enconding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: getting_started_blog_development

test:
  <<: *default
  database: getting_started_blogs_test

production:
  <<: *default
  database: getting_started_blog_production
